### ISSUE TITLE
Need a .page.gfx.current-point method

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/PDF-Lite-raku#1]
Extensive graphics and text generation require knowledge of the current point (CP) to be used on a page. I cannot find an explicit way to determine that. Some implicit ways enable capture of the CP but require lots of extra code to make it useful (but I am creating and using that code albeit incomplete).

A .newpath method would also be useful. .MoveTo's description says it can start a new path but tests using it outside a save/restore pair result in warnings.

**Comment by dwarring** [comment]
The PDF::API README refers to a "Current Point" for [path construction](https://pdf-raku.github.io/PDF-API6/#path-construction-operators). This was taken from the PDF spec.

So reasonable straight-forward to provide a `current-point` accessor that gives the current position during path construction.

path and text positioning are separate in PDF graphics. There is already a `text-position` accessor.

It probably is reasonable to allow path construction outside of save/restore block. I'll have a look.

**Comment by dwarring** [comment]
Last commit adds a `current-point` accessor to PDF::Content.

**Comment by dwarring** [comment]
So there's a `text-position` which is valid within a text block and a `current-position` which is valid while a path is being constructed.

Other thing that could be relevant is the `CTM` accessor which is the current transformation matrix' the sum total of any graphics transforms.

**Comment by dwarring** [comment]
From what I remember about PostScript, the currentpoint is used for both text and graphics.

The PDF specification has a different idea of a 'Current Point' as the position set by the last Rectangle, LineTo, CurveTo, CurveToInitial or ClosePath. This 'Current Point' only exists until the next Fill/Stroke operation which draws the graphics.

Text and graphics are independent in PDF there's a separate `Tm` text matrix.

So a PostScript like currentpoint doesn't have an exact PDF equivalent and will need some work to implement.

**Comment by tbrowder** [comment]
On Tue, Mar 9, 2021 at 13:42 David Warring ***@***.***> wrote:

> From what I remember about PostScript, the currentpoint is used for both
> text and graphics.
>
> The PDF specification has a different idea of a 'Current Point' as the
> position set by the last Rectangle, LineTo, CurveTo, CurveToInitial or
> ClosePath. This 'Current Point' only exists until the next Fill/Stroke
> operation which draws the graphics.
>
> Text and graphics are independent in PDF there's a separate Tm text
> matrix.
>
> So a PostScript like currentpoint doesn't have an exact PDF equivalent and
> will need some work to implement.
>
Thanks, David. That info helps, and I can keep track a bit better because
of it. For the moment I don't think I need any effort to implement it. I'll
close the issue for now.
