### ISSUE TITLE
The initial example in the README is incorrectly setting the document media-box.

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/PDF-Lite-raku#7]
This is a complete example I created that shows correctly setting the page media:

```
#!/bin/env raku

use PDF::Lite;

# These are some of the standard paper names and sizes copied from PDF::Content
my Array enum PageSizes is export <<
    :Letter[0,0,612,792]
    :Legal[0,0,612,1008]
    :A4[0,0,595,842]
>>;
my %m = %(PageSizes.enums);
my @m = %m.keys.sort;

# preview of title of output pdf
my $ofile = "PDF-Lite-media-simple-<media>.pdf";

my $debug = 0;
if not @*ARGS.elems {
    print qq:to/HERE/;
    Usage: {$*PROGRAM.basename} <media> [...options...]

    Produces a two-page pdf for a selected paper size
      in portrait orientation.

    Options
        s[how] - Show all known media and exit
    HERE
    exit
}

my $media;
my $show = 0;
for @*ARGS {
    when /^ :i s / {
        ++$show;
        last
    }
    default {
        # the media selection
        $media = $_.tc;
    }
}

if $show {
    say "Media:";
    say "  $_" for @m;
    say "\nThat's all for now, folks!";
    exit;
}

unless %m{$media}:exists {
    die "FATAL: Unknown media named '$media'";
}

# final title of output pdf
$ofile = "PDF-Lite-media-simple-{$media}.pdf";

my $pdf = PDF::Lite.new;
# NOTE: README shows "$pdf.media-box[] = ..."
$pdf.media-box = %(PageSizes.enums){$media};
my $font = $pdf.core-font(:family<Helvetica>, :weight<bold>);
my $cx = 0.5 * ($pdf.media-box[2] - $pdf.media-box[0]);
my $cy = 0.5 * ($pdf.media-box[3] - $pdf.media-box[1]);
my @position = [$cx, $cy];

# first page
my $page = $pdf.add-page;
$page.graphics: {
    my @box = .say: "First page", :@position, :$font, :align<center>, :valign<center>;
}

# second page
$page = $pdf.add-page;
$page.graphics: {
    my @box = .say: "Second page", :@position, :$font, :align<center>, :valign<center>;
}

# finish the document
$pdf.save-as: $ofile;

say "See output file: $ofile";
```

**Comment by dwarring** [comment]
@tbrowder 
Is it just that the initial example isn't showing enough? I've included a more detailed example in the [README](https://github.com/pdf-raku/PDF-Lite-raku#page-sizes).

In particular `PageSizes` and `to-landscape` can be imported: `use PDF::Content::Page :PageSizes, :&to-landscape;`

**Comment by tbrowder** [comment]
On Fri, Apr 21, 2023 at 12:27 David Warring ***@***.***>
wrote:

> @tbrowder <https://github.com/tbrowder>
> Is it just that the initial example isn't showing enough? I've included a
> more detailed example in the README
> <https://github.com/pdf-raku/PDF-Lite-raku#page-sizes>.
>
David, the main problem  had was assigning to the .media-box. The example
shows:

     $pdf.media-box[] = ‘Letter’;

and it didn’t work.

I had to do this:

     $pdf. media-box = [0, 0, 500, 500];
      # note  no square brackets on media-box

To get reliable results.

> In particular PageSizes and to-landscape can be imported: use
> PDF::Content::Page :PageSizes, :&to-landscape;g
>
That’s good to know. I wasn’t real sure how to get that done. After several
false tries I gave up.  Thanks.

-Tom

**Comment by tbrowder** [comment]
Thanks!
